# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7aa96570d189755a9f6360de05935eb62801be827f2a1b82893bb0608a6b0d2a7200b44f96fc8acb8b00ebb24702d8fc9e247dde45e7614495ac1d17a1b189cb

test:
  secret_key_base: 2ba90137b1898f86e8bb19d63503b601cd7246e66bf8ccd3201f4d4087b78d0daf9a98532e5cc1c8b446341e3430954645e0b75a52fa41b52a3e4c500ab69886

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
